import {
  LayoutDashboard,
  Warehouse,
  Layers3,
  Users,
  Wheat,
  Skull,
  Tags,
  ClipboardCheck,
  Scale,
  Syringe,
  SunMoon,
  Truck,
  Bird,
  Link2,
  Ruler,
} from "lucide-react";

export const modules = [
  {
    key: "dashboard",
    path: "/",
    title: "Painel",
    icon: LayoutDashboard,
    inMenu: true,
  },
  {
    key: "galpoes",
    path: "/galpoes",
    title: "Galpões",
    description: "Cadastro da estrutura física onde os lotes são alojados.",
    icon: Warehouse,
    endpoint: "/galpoes",
    inMenu: true,
    group: "Produção",
    writeRoles: ["admin"],
    columns: [
      { key: "id", label: "ID" },
      { key: "descritivo", label: "Descritivo" },
      { key: "capacidade", label: "Capacidade" },
    ],
    fields: [
      { name: "descritivo", label: "Descritivo", type: "text", required: true },
      { name: "capacidade", label: "Capacidade", type: "number", required: true },
    ],
  },
  {
    key: "lotes",
    path: "/lotes",
    title: "Lotes",
    description: "Unidade central da granja: cada ciclo produtivo vive em um lote.",
    icon: Layers3,
    endpoint: "/lotes",
    inMenu: true,
    group: "Produção",
    writeRoles: ["admin"],
    extraActions: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "galpao_id", label: "Galpão" },
      { key: "linhagem", label: "Linhagem" },
      { key: "quantidade_inicial", label: "Qtd. inicial" },
      { key: "data_entrada", label: "Entrada" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "galpao_id", label: "Galpão", type: "relation", relation: "galpoes", required: true },
      { name: "data_entrada", label: "Data de entrada", type: "date", required: true },
      { name: "quantidade_inicial", label: "Quantidade inicial", type: "number", required: true },
      {
        name: "linhagem",
        label: "Linhagem",
        type: "select",
        required: true,
        options: [
          { value: "Cobb", label: "Cobb" },
          { value: "Ross", label: "Ross" },
        ],
      },
      { name: "peso_medio_inicial", label: "Peso médio inicial (kg)", type: "number", step: "0.01", required: true },
    ],
  },
  {
    key: "entradas",
    path: "/entradas",
    title: "Entradas",
    description: "Registro logístico da chegada das aves: procedência, técnico e transporte.",
    icon: Truck,
    endpoint: "/entrada",
    inMenu: true,
    group: "Produção",
    writeRoles: ["admin", "funcionario"],
    columns: [
      { key: "id", label: "ID" },
      { key: "lote_id", label: "Lote" },
      { key: "procedencia", label: "Procedência" },
      { key: "tecnico", label: "Técnico" },
      { key: "motorista", label: "Motorista" },
      { key: "placa_caminhao", label: "Placa" },
    ],
    fields: [
      { name: "lote_id", label: "Lote", type: "relation", relation: "lotes", required: true },
      { name: "data_hora", label: "Data e hora", type: "datetime-local", required: true },
      { name: "procedencia", label: "Procedência", type: "text", required: true },
      { name: "tecnico", label: "Técnico", type: "text", required: true },
      { name: "motorista", label: "Motorista", type: "text", required: true },
      { name: "placa_caminhao", label: "Placa do caminhão", type: "text", required: true },
    ],
  },
  {
    key: "matrizes",
    path: "/matrizes",
    title: "Matrizes",
    description: "Origem genética do lote: quantidade alojada, idade e linhagem da matriz.",
    icon: Bird,
    endpoint: "/matriz",
    inMenu: true,
    group: "Produção",
    writeRoles: ["admin"],
    columns: [
      { key: "id", label: "ID" },
      { key: "lote_id", label: "Lote" },
      { key: "lote_matriz", label: "Lote matriz" },
      { key: "quantidade_alojada", label: "Qtd. alojada" },
      { key: "idade", label: "Idade" },
      { key: "linhagem", label: "Linhagem" },
    ],
    fields: [
      { name: "lote_id", label: "Lote", type: "relation", relation: "lotes", required: true },
      { name: "quantidade_alojada", label: "Quantidade alojada", type: "number", required: true },
      { name: "lote_matriz", label: "Lote da matriz", type: "number", required: true },
      { name: "idade", label: "Idade (dias)", type: "number", required: true },
      { name: "linhagem", label: "Linhagem", type: "text", required: true },
    ],
  },
  {
    key: "racoes",
    path: "/racoes",
    title: "Rações",
    description: "Controle de recebimento e estoque de ração por lote.",
    icon: Wheat,
    endpoint: "/racoes",
    inMenu: true,
    group: "Manejo",
    writeRoles: ["admin", "funcionario"],
    columns: [
      { key: "id", label: "ID" },
      { key: "lote_id", label: "Lote" },
      { key: "tipo", label: "Tipo" },
      { key: "quantidade", label: "Quantidade" },
      { key: "estoque", label: "Estoque" },
      { key: "motorista", label: "Motorista" },
      { key: "data", label: "Data", format: "date" },
    ],
    fields: [
      { name: "lote_id", label: "Lote", type: "relation", relation: "lotes", required: true },
      { name: "data", label: "Data", type: "datetime-local", required: true },
      { name: "motorista", label: "Motorista", type: "text", required: true },
      { name: "tipo", label: "Tipo", type: "text", required: true, placeholder: "Ex.: inicial, crescimento" },
      { name: "quantidade", label: "Quantidade (kg)", type: "number", step: "0.01", required: true },
      { name: "estoque", label: "Estoque (kg)", type: "number", step: "0.01", required: true },
    ],
  },
  {
    key: "pesagens",
    path: "/pesagens",
    title: "Pesagens",
    description: "Acompanhamento de peso médio por idade para comparar com a curva ideal.",
    icon: Scale,
    endpoint: "/pesagens",
    inMenu: true,
    group: "Manejo",
    writeRoles: ["admin", "funcionario"],
    columns: [
      { key: "id", label: "ID" },
      { key: "lote_id", label: "Lote" },
      { key: "idade", label: "Idade (dias)" },
      { key: "peso_medio", label: "Peso médio" },
      { key: "data_pesagem", label: "Data" },
    ],
    fields: [
      { name: "lote_id", label: "Lote", type: "relation", relation: "lotes", required: true },
      { name: "idade", label: "Idade (dias)", type: "number", required: true },
      { name: "peso_medio", label: "Peso médio (kg)", type: "number", step: "0.001", required: true },
      { name: "data_pesagem", label: "Data da pesagem", type: "date", required: true },
    ],
  },
  {
    key: "peso-ideal",
    path: "/peso-ideal",
    title: "Peso ideal",
    description: "Tabela de referência de peso por idade da linhagem trabalhada.",
    icon: Ruler,
    endpoint: "/pesoideal",
    inMenu: true,
    group: "Manejo",
    writeRoles: ["admin"],
    columns: [
      { key: "id", label: "ID" },
      { key: "idade", label: "Idade (dias)" },
      { key: "peso_ideal", label: "Peso ideal (kg)" },
    ],
    fields: [
      { name: "idade", label: "Idade (dias)", type: "number", required: true },
      { name: "peso_ideal", label: "Peso ideal (kg)", type: "number", step: "0.001", required: true },
    ],
  },
  {
    key: "luz",
    path: "/luz",
    title: "Controle de luz",
    description: "Programa luminoso do lote: faixas de idade e horas de escuro.",
    icon: SunMoon,
    endpoint: "/luz",
    inMenu: true,
    group: "Manejo",
    writeRoles: ["admin", "funcionario"],
    columns: [
      { key: "id", label: "ID" },
      { key: "lote_id", label: "Lote" },
      { key: "idade_inicial", label: "Idade inicial" },
      { key: "idade_final", label: "Idade final" },
      { key: "horas_escuro", label: "Horas de escuro" },
    ],
    fields: [
      { name: "lote_id", label: "Lote", type: "relation", relation: "lotes", required: true },
      { name: "idade_inicial", label: "Idade inicial", type: "number", required: true },
      { name: "idade_final", label: "Idade final", type: "number", required: true },
      { name: "horas_escuro", label: "Horas de escuro", type: "number", step: "0.01", required: true },
    ],
  },
  {
    key: "mortalidades",
    path: "/mortalidades",
    title: "Mortalidade",
    description: "Baixas diárias classificadas por causa, com total calculado no servidor.",
    icon: Skull,
    endpoint: "/mortalidades",
    inMenu: true,
    group: "Sanidade",
    writeRoles: ["admin", "funcionario"],
    columns: [
      { key: "id", label: "ID" },
      { key: "lote_id", label: "Lote" },
      { key: "data_mortalidade", label: "Data", format: "date" },
      { key: "idade", label: "Idade" },
      { key: "natural", label: "Natural" },
      { key: "colapso", label: "Colapso" },
      { key: "ascite", label: "Ascite" },
      { key: "refugo", label: "Refugo" },
      { key: "problema_locomotor", label: "Locomotor" },
      { key: "total_mortalidade", label: "Total" },
    ],
    fields: [
      { name: "lote_id", label: "Lote", type: "relation", relation: "lotes", required: true },
      { name: "data_mortalidade", label: "Data", type: "datetime-local", required: true },
      { name: "idade", label: "Idade (dias)", type: "number", required: true },
      { name: "natural", label: "Natural", type: "number", required: true },
      { name: "colapso", label: "Colapso", type: "number", required: true },
      { name: "ascite", label: "Ascite", type: "number", required: true },
      { name: "refugo", label: "Refugo", type: "number", required: true },
      { name: "problema_locomotor", label: "Problema locomotor", type: "number", required: true },
    ],
  },
  {
    key: "vacinas",
    path: "/vacinas",
    title: "Vacinas",
    description: "Aplicações vacinais do lote, com partida e avaliação de eficiência.",
    icon: Syringe,
    endpoint: "/vacinas",
    inMenu: true,
    group: "Sanidade",
    writeRoles: ["admin", "funcionario"],
    columns: [
      { key: "id", label: "ID" },
      { key: "lote_id", label: "Lote" },
      { key: "produto", label: "Produto" },
      { key: "n_partida", label: "Partida" },
      { key: "eficiencia", label: "Eficiência", badge: true },
      { key: "data_vacina", label: "Data" },
    ],
    fields: [
      { name: "lote_id", label: "Lote", type: "relation", relation: "lotes", required: true },
      { name: "data_vacina", label: "Data da vacina", type: "date", required: true },
      { name: "produto", label: "Produto", type: "text", required: true },
      { name: "n_partida", label: "Nº da partida", type: "text", required: true },
      {
        name: "eficiencia",
        label: "Eficiência",
        type: "select",
        required: true,
        options: [
          { value: "BOA", label: "Boa" },
          { value: "REGULAR", label: "Regular" },
          { value: "RUIM", label: "Ruim" },
        ],
      },
    ],
  },
  {
    key: "matriz-vacina",
    path: "/matriz-vacina",
    title: "Vacina da matriz",
    description: "Vínculo N:N entre matrizes e vacinas aplicadas na origem genética.",
    icon: Link2,
    endpoint: "/matrizvacina",
    inMenu: true,
    group: "Sanidade",
    writeRoles: ["admin", "funcionario"],
    columns: [
      { key: "id", label: "ID" },
      { key: "matriz_id", label: "Matriz" },
      { key: "vacina_id", label: "Vacina" },
    ],
    fields: [
      { name: "matriz_id", label: "Matriz", type: "relation", relation: "matrizes", required: true },
      { name: "vacina_id", label: "Vacina", type: "relation", relation: "vacinas", required: true },
    ],
  },
  {
    key: "categorias",
    path: "/categorias",
    title: "Categorias",
    description: "Critérios usados nas avaliações de alojamento (cama, bebedouro, etc.).",
    icon: Tags,
    endpoint: "/categorias",
    inMenu: true,
    group: "Qualidade",
    writeRoles: ["admin"],
    columns: [
      { key: "id", label: "ID" },
      { key: "descritivo", label: "Descritivo" },
    ],
    fields: [
      { name: "descritivo", label: "Descritivo", type: "text", required: true },
    ],
  },
  {
    key: "avaliacoes",
    path: "/avaliacoes",
    title: "Avaliações",
    description: "Checklist de alojamento por categoria, com resultado e valor observado.",
    icon: ClipboardCheck,
    endpoint: "/avaliacoes",
    inMenu: true,
    group: "Qualidade",
    writeRoles: ["admin", "funcionario"],
    columns: [
      { key: "id", label: "ID" },
      { key: "lote_id", label: "Lote" },
      { key: "categoria_id", label: "Categoria" },
      { key: "resultado", label: "Resultado", badge: true },
      { key: "valor", label: "Valor" },
      { key: "data_avaliacao", label: "Data", format: "date" },
    ],
    fields: [
      { name: "lote_id", label: "Lote", type: "relation", relation: "lotes", required: true },
      { name: "categoria_id", label: "Categoria", type: "relation", relation: "categorias", required: true },
      {
        name: "resultado",
        label: "Resultado",
        type: "select",
        required: true,
        options: [
          { value: "SIM", label: "Sim" },
          { value: "NÃO", label: "Não" },
        ],
      },
      { name: "valor", label: "Valor", type: "number", step: "0.01", required: true },
      { name: "data_avaliacao", label: "Data da avaliação", type: "datetime-local", required: true },
    ],
  },
  {
    key: "usuarios",
    path: "/usuarios",
    title: "Usuários",
    description: "Contas de acesso. Apenas administradores gerenciam este módulo.",
    icon: Users,
    endpoint: "/usuarios",
    inMenu: true,
    group: "Sistema",
    writeRoles: ["admin"],
    adminOnly: true,
    columns: [
      { key: "id", label: "ID" },
      { key: "nome", label: "Nome" },
      { key: "email", label: "E-mail" },
      { key: "perfil", label: "Perfil", badge: true },
    ],
    fields: [
      { name: "nome", label: "Nome", type: "text", required: true },
      { name: "email", label: "E-mail", type: "email", required: true },
      { name: "senha", label: "Senha", type: "password", requiredOnCreate: true },
    ],
  },
];

export const crudModules = modules.filter((item) => item.endpoint);

export function getModule(key) {
  return modules.find((item) => item.key === key);
}
